<?php
$title = $this->translate('Add new poll');
$this->headTitle($title);
?>
<?php
$form->setAttribute('action', $this->url('poll', ['action' => 'add']));
$form->get('submit')->setValue($this->translate('Add poll'));
$form->prepare();
?>


<div class="content bg-gray-lighter">
    <div class="row items-push">
        <div class="col-sm-7">
            <h1 class="page-heading">
                <?= $this->escapeHtml($title) ?>
            </h1>
        </div>
        <div class="col-sm-5 text-right hidden-xs">
            <ol class="breadcrumb push-10-t">
                <li><a class="link-effect" href="<?php echo $this->url('poll'); ?>"><?php echo $this->translate('Polls list');?></a></li>
                <li><?= $this->escapeHtml($title) ?></li>
            </ol>
        </div>
    </div>
</div>
<div class="content content-narrow">
    <?php echo $this->form()->openTag($form);?>
    <div class="row">
        <div class="col-md-9">
            <div class="block">
                <div class="block-header">
                    <h3 class="block-title"><?php echo $this->translate('General');?></h3>
                    <!--<ul class="block-options">
                        <li>
                            <button type="button"><i class="si si-settings"></i></button>
                        </li>
                    </ul>-->
                </div>
                <div class="block-content block-content-narrow">
                    <?php echo $this->formHidden($form->get('id'));?>
                    <div class="form-group <?php echo !empty($form->get('event')->getMessages())?'has-error':'';?>">
                        <div class="col-sm-12">
                            <div class="form-material">
                                <label><?php echo $this->translate('Event');?></label>
                                <?php echo $this->formElement($form->get('event')); ?>
                                <div class="help-block text-right animated fadeInDown form-error">
                                    <?php echo $this->formElementErrors($form->get('event'));?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group <?php echo !empty($form->get('question')->getMessages())?'has-error':'';?>">
                        <div class="col-sm-12">
                            <div class="form-material">
                                <label><?php echo $this->translate('Question');?></label>
                                <?php echo $this->formElement($form->get('question')); ?>
                                <div class="help-block text-right animated fadeInDown form-error">
                                    <?php echo $this->formElementErrors($form->get('question'));?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group <?php echo !empty($form->get('response')->getMessages())?'has-error':'';?>">
                        <div class="col-sm-12">
                            <div class="form-material">
                                <label><?php echo $this->translate('Responses');?></label>
                                <ol class="responses">
                                    <li class="form-material"><input type="text" name="responses[1]" class="form-control" /></li>
                                    <li class="form-material"><input type="text" name="responses[2]" class="form-control" /></li>
                                </ol>
                                <div class="help-block text-right animated fadeInDown form-error">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group <?php echo !empty($form->get('status')->getMessages())?'has-error':'';?>">
                        <div class="col-sm-12">
                            <div class="form-material">
                                <label><?php echo $this->translate('Status');?></label>
                                <?php echo $this->formElement($form->get('status')); ?>
                                <div class="help-block text-right animated fadeInDown form-error">
                                    <?php echo $this->formElementErrors($form->get('status'));?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group text-right">
                        <?php echo $this->formElement($form->get('csrf')); ?>
                        <?php echo $this->formSubmit($form->get('submit'));?>
                    </div>     
                </div>
            </div>
        </div>
    </div>
    <?php echo $this->form()->closeTag();?>
</div>