<?php
$title = $this->translate('Edit event');
$this->headTitle($title);
?>
<?php
$form->setAttribute('action', $this->url('event', [
    'action' => 'edit',
    'id'     => $id,
]));
$form->get('submit')->setValue($this->translate('Edit event'));
$form->prepare();
?>


<div class="content bg-gray-lighter">
    <div class="row items-push">
        <div class="col-sm-7">
            <h1 class="page-heading">
                <?= $this->escapeHtml($title) ?>
            </h1>
        </div>
        <div class="col-sm-5 text-right hidden-xs">
            <ol class="breadcrumb push-10-t">
                <li><a class="link-effect" href="<?php echo $this->url('event'); ?>"><?php echo $this->translate('Events list');?></a></li>
                <li><?= $this->escapeHtml($title) ?></li>
            </ol>
        </div>
    </div>
</div>
<div class="content content-narrow">
    <?php echo $this->form()->openTag($form);?>
    <div class="row">
        <div class="col-md-9">
            <div class="block">
                <div class="block-header">
                    <h3 class="block-title"><?php echo $this->translate('General');?></h3>
                    <!--<ul class="block-options">
                        <li>
                            <button type="button"><i class="si si-settings"></i></button>
                        </li>
                    </ul>-->
                </div>
                <div class="block-content block-content-narrow">
                    <?php echo $this->formHidden($form->get('id'));?>

                    <div class="form-group <?php echo !empty($form->get('eventName')->getMessages())?'has-error':'';?>">
                        <div class="col-sm-12">
                            <div class="form-material">
                                <label><?php echo $this->translate('Event Name');?></label>
                                <?php echo $this->formElement($form->get('eventName')); ?>
                                <div class="help-block text-right animated fadeInDown form-error">
                                    <?php echo $this->formElementErrors($form->get('eventName'));?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group  <?php echo !empty($form->get('organizer')->getMessages())?'has-error':'';?> <?php echo !empty($form->get('organizer_contact')->getMessages())?'has-error':'';?>">
                        <div class="col-md-6">
                            <div class="form-material">
                                <label><?php echo $this->translate('Organizer');?></label>
                                <?php echo $this->formElement($form->get('organizer')); ?>
                                <div class="help-block text-right animated fadeInDown form-error">
                                    <?php echo $this->formElementErrors($form->get('organizer'));?>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-material">
                                <label><?php echo $this->translate('Organizer contact');?></label>
                                <?php echo $this->formElement($form->get('organizer_contact')); ?>
                                <div class="help-block text-right animated fadeInDown form-error">
                                    <?php echo $this->formElementErrors($form->get('organizer_contact'));?>
                                </div>
                            </div>
                        </div>             
                    </div>
                    <div class="form-group  <?php echo !empty($form->get('description')->getMessages())?'has-error':'';?>">
                        <div class="col-sm-12">
                            <div class="form-material">
                                <label><?php echo $this->translate('Description');?></label>
                                <?php echo $this->formElement($form->get('description')); ?>
                                <div class="help-block text-right animated fadeInDown form-error">
                                    <?php echo $this->formElementErrors($form->get('description'));?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group  <?php echo !empty($form->get('startDate')->getMessages())?'has-error':'';?> <?php echo !empty($form->get('endDate')->getMessages())?'has-error':'';?>">
                        <div class="col-sm-6">
                            <div class="form-material">
                                <label><?php echo $this->translate('Start Date');?></label>
                                <?php echo $this->formElement($form->get('startDate')); ?>
                                <div class="help-block text-right animated fadeInDown form-error">
                                    <?php echo $this->formElementErrors($form->get('startDate'));?>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-material">
                                <label><?php echo $this->translate('End Date');?></label>
                                <?php echo $this->formElement($form->get('endDate')); ?>
                                <div class="help-block text-right animated fadeInDown form-error">
                                    <?php echo $this->formElementErrors($form->get('endDate'));?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group  <?php echo !empty($form->get('country')->getMessages())?'has-error':'';?> <?php echo !empty($form->get('city')->getMessages())?'has-error':'';?>">
                        <div class="col-md-6">
                            <div class="form-material">
                                <label><?php echo $this->translate('Country');?></label>
                                <?php echo $this->formElement($form->get('country')); ?>
                                <div class="help-block text-right animated fadeInDown form-error">
                                    <?php echo $this->formElementErrors($form->get('country'));?>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-material">
                                <label><?php echo $this->translate('City');?></label>
                                <?php echo $this->formElement($form->get('city')); ?>
                                <div class="help-block text-right animated fadeInDown form-error">
                                    <?php echo $this->formElementErrors($form->get('city'));?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group  <?php echo !empty($form->get('address')->getMessages())?'has-error':'';?>">
                        <div class="col-sm-12">
                            <div class="form-material">
                                <label><?php echo $this->translate('Address');?></label>
                                <?php echo $this->formElement($form->get('address')); ?>
                                <div class="help-block text-right animated fadeInDown form-error">
                                    <?php echo $this->formElementErrors($form->get('address'));?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group  <?php echo !empty($form->get('picture')->getMessages())?'has-error':'';?>">
                        <div class="col-sm-12">
                            <div class="form-material">
                                <label><?php echo $this->translate('Image/Logo');?></label>
                                <?php echo $this->formElement($form->get('picture')); ?>
                                <div class="help-block text-right animated fadeInDown form-error">
                                    <?php echo $this->formElementErrors($form->get('picture'));?>
                                </div>
                                <img src="<?= $this->url('images', ['action'=>'file'], ['query'=>['name'=> $form->get('picture')->getValue(), 'thumbnail'=>true]]); ?>" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="block">
                <div class="block-header">
                    <h3 class="block-title"><?php echo $this->translate('Organizer contact');?></h3>
                    <!--<<ul class="block-options">
                        <li>
                            <a type="button" ><i class="si si-users"></i> Add user</a>
                        </li>
                    </ul>-->
                </div>
                <div class="block-content block-content-narrow">
                    <div class="form-group <?php echo !empty($form->get('organizer_contact')->getMessages())?'has-error':'';?>">
                        <div class="col-sm-12">
                            <div class="form-material">
                                <label><?php echo $this->translate('Name');?></label>
                                <?php echo $this->formElement($form->get('organizer_contact')); ?>
                                <div class="help-block text-right animated fadeInDown form-error">
                                    <?php echo $this->formElementErrors($form->get('organizer_contact'));?>
                                </div>
                            </div>
                        </div>
                    </div>                 
                </div>
            </div>
            <div class="block">
                <div class="block-header">
                    <h3 class="block-title"><?php echo $this->translate('Social network');?></h3>
                    <!--<ul class="block-options">
                        <li>
                            <button type="button"><i class="si si-settings"></i></button>
                        </li>
                    </ul>-->
                </div>
                <div class="block-content block-content-narrow">
                    <div class="form-group  <?php echo !empty($form->get('facebook')->getMessages())?'has-error':'';?>">
                        <div class="col-sm-12">
                            <div class="form-material">
                                <label><?php echo $this->translate('Facebook');?></label>
                                <?php echo $this->formElement($form->get('facebook')); ?>
                                <div class="help-block text-right animated fadeInDown form-error">
                                    <?php echo $this->formElementErrors($form->get('facebook'));?>
                                </div>
                            </div>
                        </div>
                    </div>                   
                </div>
                <div class="block-content block-content-narrow">
                    <div class="form-group  <?php echo !empty($form->get('twitter')->getMessages())?'has-error':'';?>">
                        <div class="col-sm-12">
                            <div class="form-material">
                                <label><?php echo $this->translate('Twitter');?></label>
                                <?php echo $this->formElement($form->get('twitter')); ?>
                                <div class="help-block text-right animated fadeInDown form-error">
                                    <?php echo $this->formElementErrors($form->get('twitter'));?>
                                </div>
                            </div>
                        </div>
                    </div>                   
                </div>
                <div class="block-content block-content-narrow">
                    <div class="form-group  <?php echo !empty($form->get('twitterHashTag')->getMessages())?'has-error':'';?>">
                        <div class="col-sm-12">
                            <div class="form-material">
                                <label><?php echo $this->translate('Twitter #');?></label>
                                <?php echo $this->formElement($form->get('twitterHashTag')); ?>
                                <div class="help-block text-right animated fadeInDown form-error">
                                    <?php echo $this->formElementErrors($form->get('twitterHashTag'));?>
                                </div>
                            </div>
                        </div>
                    </div>                   
                </div>
                <div class="block-content block-content-narrow">
                    <div class="form-group  <?php echo !empty($form->get('instagram')->getMessages())?'has-error':'';?>">
                        <div class="col-sm-12">
                            <div class="form-material">
                                <label><?php echo $this->translate('Instagram');?></label>
                                <?php echo $this->formElement($form->get('instagram')); ?>
                                <div class="help-block text-right animated fadeInDown form-error">
                                    <?php echo $this->formElementErrors($form->get('instagram'));?>
                                </div>
                            </div>
                        </div>
                    </div>                   
                </div>
            </div>
            <div class="block">
                <div class="block-header">
                    <h3 class="block-title"><?php echo $this->translate('Event settings');?></h3>
                    <!--<ul class="block-options">
                        <li>
                            <button type="button"><i class="si si-settings"></i></button>
                        </li>
                    </ul>-->
                </div>
                <div class="block-content block-content-narrow">
                    <div class="form-group <?php echo !empty($form->get('status')->getMessages())?'has-error':'';?>">
                        <div class="col-sm-12">
                            <div class="form-material">
                                <label><?php echo $this->translate('Status');?></label>
                                <?php echo $this->formElement($form->get('status')); ?>
                                <div class="help-block text-right animated fadeInDown form-error">
                                    <?php echo $this->formElementErrors($form->get('status'));?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group text-right">
                        <?php echo $this->formElement($form->get('csrf')); ?>
                        <?php echo $this->formSubmit($form->get('submit'));?>
                    </div>                   
                </div>
            </div>
        </div>
    </div>
    <?php echo $this->form()->closeTag();?>
</div>