<?php
$title = $this->translate('Edit user');
$this->headTitle($title);
$form->setAttribute('action', $this->url('user', [
    'action' => 'edit',
    'id'     => $user->id,
]));
$form->get('submit')->setValue($this->translate('Save changes'));
$form->get('password')->setValue($this->password);

$form->prepare();
?>

<div class="content bg-gray-lighter">
    <div class="row items-push">
        <div class="col-sm-7">
            <h1 class="page-heading">
                <?= $this->escapeHtml($title) ?>
            </h1>
        </div>
        <div class="col-sm-5 text-right hidden-xs">
            <ol class="breadcrumb push-10-t">
                <li><a class="link-effect" href="<?php echo $this->url('user'); ?>"><?php echo $this->translate('Users list');?></a></li>
                <li><?php echo $this->translate('Edit user');?></li>
            </ol>
        </div>
    </div>
</div>
<div class="content content-narrow">
    <?php echo $this->form()->openTag($form);?>
    <div class="row">
        <div class="col-md-6">
            <div class="block">
                <div class="block-header">
                    <h3 class="block-title"><?php echo $this->translate('General');?></h3>
                    <!--<ul class="block-options">
                        <li>
                            <button type="button"><i class="si si-settings"></i></button>
                        </li>
                    </ul>-->
                </div>
                <div class="block-content block-content-narrow">
                    <?php echo $this->formHidden($form->get('id'));?>

                    <div class="form-group <?php echo !empty($form->get('username')->getMessages())?'has-error':'';?>">
                        <div class="col-sm-9">
                            <div class="form-material">
                                <label><?php echo $this->translate('Username');?></label>
                                <?php echo $this->formElement($form->get('username')); ?>
                                <div class="help-block text-right animated fadeInDown form-error">
                                    <?php echo $this->formElementErrors($form->get('username'));?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group  <?php echo !empty($form->get('email')->getMessages())?'has-error':'';?>">
                        <div class="col-sm-9">
                            <div class="form-material">
                                <label><?php echo $this->translate('Email');?></label>
                                <?php echo $this->formElement($form->get('email')); ?>
                                <div class="help-block text-right animated fadeInDown form-error">
                                    <?php echo $this->formElementErrors($form->get('email'));?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group  <?php echo !empty($form->get('firstname')->getMessages())?'has-error':'';?>">
                        <div class="col-sm-9">
                            <div class="form-material">
                                <label><?php echo $this->translate('Firstname');?></label>
                                <?php echo $this->formElement($form->get('firstname')); ?>
                                <div class="help-block text-right animated fadeInDown form-error">
                                    <?php echo $this->formElementErrors($form->get('firstname'));?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group  <?php echo !empty($form->get('lastname')->getMessages())?'has-error':'';?>">
                        <div class="col-sm-9">
                            <div class="form-material">
                                <label><?php echo $this->translate('Lastname');?></label>
                                <?php echo $this->formElement($form->get('lastname')); ?>
                                <div class="help-block text-right animated fadeInDown form-error">
                                    <?php echo $this->formElementErrors($form->get('lastname'));?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group  <?php echo !empty($form->get('role')->getMessages())?'has-error':'';?>">
                        <div class="col-sm-9">
                            <div class="form-material">
                                <label><?php echo $this->translate('Role');?></label>
                                <div>
                                    <?php echo $this->formElement($form->get('role')); ?>
                                </div>
                                <div class="help-block text-right animated fadeInDown form-error">
                                    <?php echo $this->formElementErrors($form->get('role'));?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <?php echo $this->formElement($form->get('csrf')); ?>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="block">
                <div class="block-header">
                    <h3 class="block-title"><?php echo $this->translate('Social media');?></h3>
                    <!--<ul class="block-options">
                        <li>
                            <button type="button"><i class="si si-settings"></i></button>
                        </li>
                    </ul>-->
                </div>
                <div class="block-content block-content-narrow">
                    <div class="form-group <?php echo !empty($form->get('facebook')->getMessages())?'has-error':'';?>">
                        <div class="col-sm-9">
                            <div class="form-material">
                                <label><?php echo $this->translate('Facebook link');?></label>
                                <?php echo $this->formElement($form->get('facebook')); ?>
                                <div class="help-block text-right animated fadeInDown form-error">
                                    <?php echo $this->formElementErrors($form->get('facebook'));?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group  <?php echo !empty($form->get('linkedin')->getMessages())?'has-error':'';?>">
                        <div class="col-sm-9">
                            <div class="form-material">
                                <label><?php echo $this->translate('LinkedIn link');?></label>
                                <?php echo $this->formElement($form->get('linkedin')); ?>
                                <div class="help-block text-right animated fadeInDown form-error">
                                    <?php echo $this->formElementErrors($form->get('linkedin'));?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group  <?php echo !empty($form->get('avatar')->getMessages())?'has-error':'';?>">
                        <div class="col-sm-9">
                            <div class="form-material">
                                <label><?php echo $this->translate('Avatar');?></label>
                                <?php echo $this->formElement($form->get('avatar')); ?>
                                <div class="help-block text-right animated fadeInDown form-error">
                                    <?php echo $this->formElementErrors($form->get('avatar'));?>
                                </div>
                            </div>
                        </div>
                    </div>                    
                </div>
            </div>
            <div class="block">
                <div class="block-header">
                    <h3 class="block-title"><?php echo $this->translate('Admin tasks');?></h3>
                    <!--<ul class="block-options">
                        <li>
                            <button type="button"><i class="si si-settings"></i></button>
                        </li>
                    </ul>-->
                </div>
                <div class="block-content block-content-narrow">
                    <div class="form-group  <?php echo !empty($form->get('enabled')->getMessages())?'has-error':'';?>">
                        <div class="col-sm-12">
                            <label class="col-md-5" style="padding-top: 4px;"><?php echo $this->translate('Enable account');?></label>
                            <div class="col-md-7">
                                <?php echo $this->formElement($form->get('enabled')); ?>
                            </div>
                            <div class="help-block text-right animated fadeInDown form-error">
                                <?php echo $this->formElementErrors($form->get('enabled'));?>
                            </div>
                        </div>
                    </div>
                    <div class="form-group  <?php echo !empty($form->get('locked')->getMessages())?'has-error':'';?>">
                        <div class="col-sm-12">
                            <label class="col-md-5" style="padding-top: 4px;"><?php echo $this->translate('Lock account');?></label>
                            <div class="col-md-7">
                                <?php echo $this->formElement($form->get('locked')); ?>
                            </div>
                            <div class="help-block text-right animated fadeInDown form-error">
                                <?php echo $this->formElementErrors($form->get('locked'));?>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-12">
                            <label class="col-md-5"><?php echo $this->translate('Subscription date');?></label>
                            <div class="col-md-7">
                                <div>
                                    <?=$user->subscription_date;?>
                                </div>
                            </div>
                        </div>
                    </div>                    
                    <div class="form-group">
                        <div class="col-sm-12">
                            <label class="col-md-5"><?php echo $this->translate('last password request');?></label>
                            <div class="col-md-7">
                                <div>
                                    <?=$user->password_requested_at;?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-12">
                            <label class="col-md-5"><?php echo $this->translate('Credentials expire at');?></label>
                            <div class="col-md-7">
                                <div>
                                    <?=$user->credentials_expire_at;?>
                                </div>
                            </div>
                        </div>
                    </div>             
                </div>
            </div>
        </div>
    </div>
    <div class="block">
        <div class="block-content block-content-narrow">
            <div class="form-group text-center">
                <a href="<?=$this->url()->fromRoute('user'); ?>" class="btn btn-default"><?php echo $this->translate('Back');?></a>
                <?php echo $this->formSubmit($form->get('submit'));?>
            </div>
        </div>
    </div>
    <?php echo $this->form()->closeTag();?>
</div>