<?php
$title = $this->translate('Edit post');
$this->headTitle($title);
?>
<?php
$form->setAttribute('action', $this->url('feed', [
    'action' => 'edit',
    'id'     => $id,
]));
$form->get('submit')->setValue($this->translate('Edit post'));
$form->prepare();
?>


<div class="content bg-gray-lighter">
    <div class="row items-push">
        <div class="col-sm-7">
            <h1 class="page-heading">
                <?= $this->escapeHtml($title) ?>
            </h1>
        </div>
        <div class="col-sm-5 text-right hidden-xs">
            <ol class="breadcrumb push-10-t">
                <li><a class="link-effect" href="<?php echo $this->url('feed'); ?>"><?php echo $this->translate('Posts list');?></a></li>
                <li><?= $this->escapeHtml($title) ?></li>
            </ol>
        </div>
    </div>
</div>
<div class="content content-narrow">
    <?php echo $this->form()->openTag($form);?>
    <div class="row">
        <div class="col-md-9">
            <div class="block">
                <div class="block-header">
                    <h3 class="block-title"><?php echo $this->translate('General');?></h3>
                    <!--<ul class="block-options">
                        <li>
                            <button type="button"><i class="si si-settings"></i></button>
                        </li>
                    </ul>-->
                </div>
                <div class="block-content block-content-narrow">
                    <?php echo $this->formHidden($form->get('id'));?>

                    <div class="form-group <?php echo !empty($form->get('title')->getMessages())?'has-error':'';?>">
                        <div class="col-sm-12">
                            <div class="form-material">
                                <label><?php echo $this->translate('Title');?></label>
                                <?php echo $this->formElement($form->get('title')); ?>
                                <div class="help-block text-right animated fadeInDown form-error">
                                    <?php echo $this->formElementErrors($form->get('title'));?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group  <?php echo !empty($form->get('content')->getMessages())?'has-error':'';?>">
                        <div class="col-sm-12">
                            <div class="form-material">
                                <label><?php echo $this->translate('Content');?></label>
                                <?php echo $this->formElement($form->get('content')); ?>
                                <div class="help-block text-right animated fadeInDown form-error">
                                    <?php echo $this->formElementErrors($form->get('content'));?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group  <?php echo !empty($form->get('excerpt')->getMessages())?'has-error':'';?>">
                        <div class="col-sm-12">
                            <div class="form-material">
                                <label><?php echo $this->translate('Excerpt');?></label>
                                <?php echo $this->formElement($form->get('excerpt')); ?>
                                <div class="help-block text-right animated fadeInDown form-error">
                                    <?php echo $this->formElementErrors($form->get('excerpt'));?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group  <?php echo !empty($form->get('picture')->getMessages())?'has-error':'';?>">
                        <div class="col-sm-12">
                            <div class="form-material">
                                <label><?php echo $this->translate('Image/Video');?></label>
                                <?php echo $this->formElement($form->get('picture')); ?>
                                <div class="help-block text-right animated fadeInDown form-error">
                                    <?php echo $this->formElementErrors($form->get('picture'));?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="block">
                <div class="block-header">
                    <h3 class="block-title"><?php echo $this->translate('Post settings');?></h3>
                    <!--<ul class="block-options">
                        <li>
                            <button type="button"><i class="si si-settings"></i></button>
                        </li>
                    </ul>-->
                </div>
                <div class="block-content block-content-narrow">
                    <div class="form-group <?php echo !empty($form->get('status')->getMessages())?'has-error':'';?>">
                        <div class="col-sm-12">
                            <div class="form-material">
                                <label><?php echo $this->translate('Status');?></label>
                                <?php echo $this->formElement($form->get('status')); ?>
                                <div class="help-block text-right animated fadeInDown form-error">
                                    <?php echo $this->formElementErrors($form->get('status'));?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group text-right">
                        <?php echo $this->formElement($form->get('csrf')); ?>
                        <?php echo $this->formSubmit($form->get('submit'));?>
                    </div>                   
                </div>
            </div>
        </div>
    </div>
    <?php echo $this->form()->closeTag();?>
</div>