<?php
$title = $this->translate('Feed Karma');
$this->headTitle($title);
?>
<!-- Page Header -->
<div class="content bg-gray-lighter">
    <div class="row items-push">
        <div class="col-sm-7">
            <h1 class="page-heading">
                <?= $this->escapeHtml($title) ?>
            </h1>
        </div>
        <div class="col-sm-5 text-right hidden-xs">
            <ol class="breadcrumb push-10-t">
                <li><a class="link-effect" href="<?php echo $this->url('feed'); ?>"><?php echo $this->translate('Posts list');?></a></li>
                <li><?= $this->escapeHtml($title) ?></li>
            </ol>
        </div>
    </div>
</div>

<!-- Page Content -->
<div class="content">
    <!-- Dynamic Table Full -->
    <div class="block">
        <div class="block-content">
            <!-- DataTables init on table by adding .js-dataTable-full class, functionality initialized in js/pages/base_tables_datatables.js -->
            <table class="table table-bordered table-striped js-dataTable-full">
                <thead>
                    <tr>
                        <th><?php echo $this->translate('ID');?></th>
                        <th><?php echo $this->translate('Author');?></th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    if(count($karma)>0):
                        foreach ($karma as $k) : ?>
                            <tr>
                                <td><?= $this->escapeHtml($k['id']) ?></td>
                                <td><?= $this->escapeHtml($k['author']) ?></td>
                            </tr>
                        <?php endforeach;
                            else:
                        ?>
                            <tr><td colspan="7"><?php echo $this->translate('No Karma found for this post');?></td></tr>
                        <?php endif;?>
                </tbody>
            </table>
        </div>
    </div>
</div>
<!-- END Page Header -->
