<!-- Hero Content -->
<div class="bg-primary-dark">
    <section class="content content-full content-boxed overflow-hidden">
        <!-- Section Content -->
        <div class="push-100-t push-50 text-center">
            <h1 class="h2 text-white push-10 visibility-hidden" data-toggle="appear" data-class="animated fadeInDown">Log in to your dashboard.</h1>
            <h2 class="h5 text-white-op visibility-hidden" data-toggle="appear" data-class="animated fadeInDown">Unlimited ideas. Unlimited power. Unlimited joy. Unlimited opportunities.</h2>
        </div>
        <div class="row visibility-hidden" data-toggle="appear" data-class="animated fadeInUp">
            <div class="col-sm-8 col-sm-offset-2">
                <img class="img-responsive pull-b" src="assets/img/various/promo1.jpg" alt="">
            </div>
        </div>
        <!-- END Section Content -->
    </section>
</div>
<!-- END Hero Content -->

<!-- Log In Form -->
<div class="bg-white">
    <section class="content content-boxed">
        <!-- Section Content -->
        <div class="row items-push push-50-t push-30">
            <div class="col-md-6 col-md-offset-3">
                <form class="form-horizontal" action="index.html" method="post">
                    <div class="form-group">
                        <div class="col-xs-12">
                            <div class="form-material form-material-primary">
                                <input class="form-control" type="text" id="frontend-login-username" name="frontend-login-username" placeholder="Enter your username..">
                                <label for="frontend-login-username">Username</label>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-xs-12">
                            <div class="form-material form-material-primary">
                                <input class="form-control" type="password" id="frontend-login-password" name="frontend-login-password" placeholder="Enter your password">
                                <label for="frontend-login-password">Password</label>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-xs-12 text-center">
                            <label class="css-input switch switch-sm switch-primary">
                                <input type="checkbox" id="frontend-login-remember-me" name="frontend-login-remember-me"><span></span> Remember Me?
                            </label>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-xs-12 col-sm-6 col-sm-offset-3">
                            <button class="btn btn-block btn-primary" type="submit"><i class="fa fa-arrow-right pull-right"></i> Log in</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <!-- END Section Content -->
    </section>
</div>
<!-- END Log In Form -->

<!-- Sign Up Today -->
<div class="bg-gray-lighter">
    <section class="content content-full content-boxed">
        <!-- Section Content -->
        <div class="push-20-t push-20 text-center">
            <h3 class="h4 push-20 visibility-hidden" data-toggle="appear">Don’t have an account?</h3>
            <a class="btn btn-rounded btn-noborder btn-lg btn-success visibility-hidden" data-toggle="appear" data-class="animated bounceIn" href="frontend_signup.html">Sign Up Today</a>
        </div>
        <!-- END Section Content -->
    </section>
</div>
<!-- END Sign Up Today -->
<?php

$form = $this->form;
/**
 *
 * Set form fields classes and placeholders here
 *
 */
$form->setAttributes(array(
    'class' => 'form'
));
$form->get('usernameOrEmail')->setAttributes(array(
    'class' => 'form-control input-lg', 
    'placeholder' => $this->translate('Username or Email')
));
$form->get('password')->setAttributes(array(
    'class' => 'form-control input-lg', 
    'placeholder' => $this->translate('Password')
));
$form->get('rememberme')->setAttributes(array(
    //'class' => 'form-control input-lg', 
));
$form->get('captcha')->setAttributes(array(
    'required' => 'true',
    'class' => 'form-control input-lg',
    'placeholder' => $this->translate('Verify you are human')
));
$form->get('submit')->setAttributes(array(
    'class' => 'btn btn btn-success btn-lg',
));
$form->prepare();
?>
<div class="jumbotron">
  <h2><?php echo $this->translate('Sign In')?></h2>
    <div class="container" id="wrap">
	  <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <?php echo $this->form()->openTag($form); ?>
            <div class="row">
              <div class="col-sm-12"> 
                <?php echo $this->messages ?>      
              </div>
            </div>
            <?php
              $element = $form->get('usernameOrEmail');
              echo $this->formElement($element);
              echo $this->formElementErrors($element);
            ?>
            <?php
              $element = $form->get('password');
              echo $this->formElement($element);
              echo $this->formElementErrors($element);
            ?>
            <div class="checkbox">
            <?php
              $element = $form->get('rememberme');
              echo $this->formLabel($element, $this->formCheckbox($element), 'append');
              echo $this->formElementErrors($element);
            ?>
            </div>
            <div class="row">
              <div class="col-xs-12 col-md-12">
                <?php 
                  $element = $form->get('captcha');
                  echo $this->formElement($element);
                  echo $this->formElementErrors($element);
                ?>
              </div>
            </div>
            <div class="row">
              <div class="col-sm-12"> 
                <?php echo $this->formRow($form->get('submit'))?>              
              </div>
            </div>
            <div class="row">
              <div class="col-sm-12"> 
	            <a href="<?php echo $this->url('login', array('action' => 'signup'));?>">
	              <?php echo $this->translate('Sign up'); ?>
	            </a> |  
	            <a href="<?php echo $this->url('login', array('action' => 'reset-password'));?>">
	              <?php echo $this->translate('Forgot your password?'); ?>
	            </a>
              </div>
            </div>
            <?php 
              echo $this->formRow($form->get('csrf'));
              echo $this->form()->closeTag();
            ?>         
        </div>
      </div>            
    </div>
</div>