<?php
$form = $this->form;
/**
 *
 * Set form fields classes and placeholders here
 *
 */
$form->setAttributes(array(
    'class' => 'form'
));
$form->get('usernameOrEmail')->setAttributes(array( 
    'placeholder' => $this->translate('enter username or email')
));
$form->get('password')->setAttributes(array(
    'placeholder' => $this->translate('enter your password')
));
$form->get('rememberme')->setAttributes(array(
    //'class' => 'form-control input-lg', 
));
$form->get('captcha')->setAttributes(array(
    'required' => 'true',
    'class' => 'form-control',
    'placeholder' => $this->translate('Verify you are human')
));
$form->get('submit')->setAttributes(array(
    'class' => 'btn btn-block btn-primary',
    'label' => '<i class="fa fa-arrow-right pull-right"></i> Log in',
            'label_options' => [
                'disable_html_escape' => true,
            ]
));
$form->prepare();
?>
<!-- Hero Content -->
<div class="bg-primary-dark">
    <section class="content content-full content-boxed overflow-hidden">
        <!-- Section Content -->
        <div class="push-100-t push-50 text-center">
            <h1 class="h2 text-white push-10 visibility-hidden" data-toggle="appear" data-class="animated fadeInDown">Log in to your dashboard.</h1>
            <h2 class="h5 text-white-op visibility-hidden" data-toggle="appear" data-class="animated fadeInDown">Unlimited ideas. Unlimited power. Unlimited joy. Unlimited opportunities.</h2>
        </div>
        <div class="row visibility-hidden" data-toggle="appear" data-class="animated fadeInUp">
            <div class="col-sm-8 col-sm-offset-2">
                <img class="img-responsive pull-b" src="img/various/promo1.jpg" alt="">
            </div>
        </div>
        <!-- END Section Content -->
    </section>
</div>
<!-- END Hero Content -->

<!-- Log In Form -->
<div class="bg-white">
    <section class="content content-boxed">
        <!-- Section Content -->
        <div class="row items-push push-50-t push-30">
            <div class="col-md-6 col-md-offset-3">
                <?php echo $this->form()->openTag($form); ?>
                    <div class="form-group">
                        <div class="col-xs-12">
                            <div class="form-material form-material-primary">
                                <?php echo $this->formElement($form->get('usernameOrEmail')); ?>
                                <?php echo $this->formLabel($form->get('usernameOrEmail')); ?>
                                <?php echo $this->formElementErrors($form->get('usernameOrEmail')); ?>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-xs-12">
                            <div class="form-material form-material-primary">
                                <?php echo $this->formElement($form->get('password')); ?>
                                <?php echo $this->formLabel($form->get('password')); ?>
                                <?php echo $this->formElementErrors($form->get('password')); ?>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-xs-12">
                            <?php 
                                echo $this->formElement($form->get('captcha'));
                                echo $this->formElementErrors($form->get('captcha'));
                            ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-xs-12 text-center">
                            <label class="css-input switch switch-sm switch-primary">
                                <?php echo $this->formElement($form->get('rememberme')); ?><span></span> <?php echo $this->formLabel($form->get('rememberme')); ?>
                            </label>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-xs-12 col-sm-6 col-sm-offset-3">
                            <?php echo $this->formElement($form->get('submit'))?>
                        </div>
                    </div>
                <?php 
                echo $this->formRow($form->get('csrf'));
                echo $this->form()->closeTag();
              ?>
            </div>
            	            <a href="<?php echo $this->url('login', ['action' => 'reset-password']);?>">
	              <?php echo $this->translate('Forgot your password?'); ?>
	            </a>
        </div>
        <!-- END Section Content -->
    </section>
</div>
<!-- END Log In Form -->

<!-- Sign Up Today -->
<div class="bg-gray-lighter">
    <section class="content content-full content-boxed">
        <!-- Section Content -->
        <div class="push-20-t push-20 text-center">
            <h3 class="h4 push-20 visibility-hidden" data-toggle="appear"><?php echo $this->translate('Don’t have an account?');?></h3>
            <a class="btn btn-rounded btn-noborder btn-lg btn-success visibility-hidden" data-toggle="appear" data-class="animated bounceIn" href="<?php echo $this->url('register', ['action' => 'register']);?>">
                <?php echo $this->translate('Sign Up Today');?>
            </a>
        </div>
        <!-- END Section Content -->
    </section>
</div>
<!-- END Sign Up Today -->
