<?php

$form = $this->form;
/**
 *
 * Set form fields classes and placeholders here
 *
 */
$form->setAttributes(array(
    'class' => 'form-horizontal'
));
$form->get('username')->setAttributes(array( 
    'placeholder' => $this->translate('enter your username')
));
$form->get('firstname')->setAttributes(array( 
    'placeholder' => $this->translate('enter your first name')
));
$form->get('lastname')->setAttributes(array( 
    'placeholder' => $this->translate('enter your last name')
));
$form->get('email')->setAttributes(array( 
    'placeholder' => $this->translate('enter your email')
));
$form->get('password')->setAttributes(array(
    'placeholder' => $this->translate('enter your password')
));
$form->get('passwordConfirm')->setAttributes(array(
    'placeholder' => $this->translate('confirm your password')
));


$form->get('captcha')->setAttributes([
    'required' => 'true',
    'class' => 'form-control',
    'placeholder' => $this->translate('Verify you are human')
]);
$form->get('submit')->setAttributes([
    'class' => 'btn btn-block btn-success',
    'value' => $this->translate('Sign Up'),
]);
$form->prepare();
?>
<!-- Hero Content -->
<div class="bg-primary-dark">
    <section class="content content-full content-boxed overflow-hidden">
        <!-- Section Content -->
        <div class="push-100-t push-50 text-center">
            <h1 class="h2 text-white push-10 visibility-hidden" data-toggle="appear" data-class="animated fadeInDown">Log in to your dashboard.</h1>
            <h2 class="h5 text-white-op visibility-hidden" data-toggle="appear" data-class="animated fadeInDown">Unlimited ideas. Unlimited power. Unlimited joy. Unlimited opportunities.</h2>
        </div>
        <div class="row visibility-hidden" data-toggle="appear" data-class="animated fadeInUp">
            <div class="col-sm-8 col-sm-offset-2">
                <img class="img-responsive pull-b" src="img/various/promo1.jpg" alt="">
            </div>
        </div>
        <!-- END Section Content -->
    </section>
</div>
<!-- END Hero Content -->

<!-- Log In Form -->
<div class="bg-white">
    <section class="content content-boxed">
        <!-- Section Content -->
        <div class="row items-push push-50-t push-30">
            <div class="col-md-6 col-md-offset-3">
                <?php echo $this->form()->openTag($form); ?>
                    <div class="form-group">
                        <div class="col-xs-12">
                            <div class="form-material form-material-primary">
                                <?php echo $this->formElement($form->get('username')); ?>
                                <?php echo $this->formLabel($form->get('username')); ?>
                                <?php echo $this->formElementErrors($form->get('username')); ?>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-xs-12">
                            <div class="form-material form-material-primary">
                                <?php echo $this->formElement($form->get('email')); ?>
                                <?php echo $this->formLabel($form->get('email')); ?>
                                <?php echo $this->formElementErrors($form->get('email')); ?>
                            </div>
                        </div>
                    </div>                
                    <div class="form-group">
                        <div class="col-xs-12">
                            <div class="form-material form-material-primary">
                                <?php echo $this->formElement($form->get('password')); ?>
                                <?php echo $this->formLabel($form->get('password')); ?>
                                <?php echo $this->formElementErrors($form->get('password')); ?>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-xs-12">
                            <div class="form-material form-material-primary">
                                <?php echo $this->formElement($form->get('passwordConfirm')); ?>
                                <?php echo $this->formLabel($form->get('passwordConfirm')); ?>
                                <?php echo $this->formElementErrors($form->get('passwordConfirm')); ?>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-xs-12">
                            <div class="form-material form-material-primary">
                                <?php echo $this->formElement($form->get('firstname')); ?>
                                <?php echo $this->formLabel($form->get('firstname')); ?>
                                <?php echo $this->formElementErrors($form->get('firstname')); ?>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-xs-12">
                            <div class="form-material form-material-primary">
                                <?php echo $this->formElement($form->get('lastname')); ?>
                                <?php echo $this->formLabel($form->get('lastname')); ?>
                                <?php echo $this->formElementErrors($form->get('lastname')); ?>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="form-material form-material-primary">
                            <div class="col-md-2">
                                <?php echo $this->formLabel($form->get('registration_type')); ?>
                            </div>
                            <div class="col-md-10">
                                <?php echo $this->formElement($form->get('registration_type')); ?>
                            </div>
                        </div>
                        <?php echo $this->formElementErrors($form->get('registration_type')); ?>
                    </div>
                    <div class="form-group">
                        <div class="col-xs-12">
                            <?php 
                                echo $this->formElement($form->get('captcha'));
                                echo $this->formElementErrors($form->get('captcha'));
                            ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-xs-12 col-sm-6 col-sm-offset-3">
                            <?php echo $this->formElement($form->get('submit'))?>
                        </div>
                    </div>
                <?php 
                echo $this->formRow($form->get('csrf'));
                echo $this->form()->closeTag();
              ?>
            </div>
        </div>
        <!-- END Section Content -->
    </section>
</div>
<!-- END Log In Form -->

<!-- Log in -->
<div class="bg-gray-lighter">
    <section class="content content-full content-boxed">
        <!-- Section Content -->
        <div class="push-20-t push-20 text-center">
            <h3 class="h4 push-20 animated fadeIn" data-toggle="appear">><?php echo $this->translate('Do you already have an account?');?></h3>
            <a class="btn btn-rounded btn-noborder btn-lg btn-success animated bounceIn" data-toggle="appear" data-class="animated bounceIn" href="<?php echo $this->url('login', ['action' => 'login']);?>">
                <?php echo $this->translate('Log In');?>
            </a>
        </div>
        <!-- END Section Content -->
    </section>
</div>
<!-- END Sign Up Today -->
