<?php
$title = $this->translate('Add new feedback');
$this->headTitle($title);
?>
<?php
$form->setAttribute('action', $this->url('feedback', ['action' => 'add']));

$form->get('submit')->setValue($this->translate('Add feedback'));
?>


<div class="content bg-gray-lighter">
    <div class="row items-push">
        <div class="col-sm-7">
            <h1 class="page-heading">
                <?= $this->escapeHtml($title) ?>
            </h1>
        </div>
        <div class="col-sm-5 text-right hidden-xs">
            <ol class="breadcrumb push-10-t">
                <li><a class="link-effect" href="<?php echo $this->url('feedback'); ?>"><?php echo $this->translate('Feedback list');?></a></li>
                <li>Add</li>
            </ol>
        </div>
    </div>
</div>
<div class="content content-narrow">
    <?php echo $this->form()->openTag($form);?>
    <div class="row">
        <div class="col-md-12">
            <div class="block">
                <div class="block-content block-content-narrow">
                    <?php echo $this->formHidden($form->get('id'));?>
                    <?php echo $this->formHidden($form->get('rate'));?>
                    <div class="form-group">
                        <div class="col-sm-9">
                            <div class="form-material">
                                <label><?php echo $this->translate('Rate');?></label>
                                <div class="form-control-static">
                                    <!-- Rating Container -->
                                    <div class="js-rating" data-score="0" data-star-on="fa fa-fw fa-2x fa-star text-warning" data-star-off="fa fa-fw fa-2x fa-star text-gray"></div>
                                </div>
                                <div class="help-block text-right animated fadeInDown form-error"></div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group <?php echo !empty($form->get('text')->getMessages())?'has-error':'';?>">
                        <div class="col-sm-9">
                            <div class="form-material">
                                <label><?php echo $this->translate('Your feedback');?></label>
                                <?php echo $this->formElement($form->get('text')); ?>
                                <div class="help-block text-right animated fadeInDown form-error">
                                    <?php echo $this->formElementErrors($form->get('text'));?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-9">
                            <label><?php echo $this->translate('Highlight');?></label>
                            <?php $element = $form->get('highlight') ?>
                            <div>
                                <?php foreach ($element->getValueOptions() as $value => $label): ?>
                                    <?php $checked = $value == $element->getValue() ? 'checked="true"' : ''; ?>
                                    <label class="css-input css-radio css-radio-primary push-10-r" for="<?php echo $element->getName().$value ?>">
                                        <input id="<?php echo $element->getName().$value ?>" type="radio" name="<?php echo $element->getName() ?>" value="<?php echo $value ?>"<?php echo $checked ?>><span></span> <?php echo $label ?>
                                    </label>
                                <?php endforeach ?>
                            </div>
                            <div class="help-block text-right animated fadeInDown form-error">
                                <?php echo $this->formElementErrors($form->get('highlight'));?>
                            </div>
                        </div>
                    </div>
                    <div class="form-group text-center">
                        <?php echo $this->formElement($form->get('csrf')); ?>
                        <a href="/feedback" class="btn btn-default"><?php echo $this->translate('Back');?></a>
                        <?php echo $this->formSubmit($form->get('submit'));?>
                    </div>
                </div>
            </div>
        </div>
    <?php echo $this->form()->closeTag();?>
</div>