<?php
$title = $this->translate('Feedback list');
$this->headTitle($title);
?>
<!-- Page Header -->
<div class="content bg-gray-lighter">
    <div class="row items-push">
        <div class="col-sm-7">
            <h1 class="page-heading">
                <?= $this->escapeHtml($title) ?>
            </h1>
        </div>
        <div class="col-sm-5 text-right hidden-xs">
            <a href="<?= $this->url('feedback', ['action' => 'add']) ?>" class="btn btn-primary"><i class="fa fa-plus"></i> <?php echo $this->translate('Add new feedback');?></a>
        </div>
        <!--<div class="col-sm-5 text-right hidden-xs">
            <ol class="breadcrumb push-10-t">
                <li>Tables</li>
                <li><a class="link-effect" href="">DataTables</a></li>
            </ol>
        </div>-->
    </div>
</div>

<!-- Page Content -->
<div class="content">
    <!-- Dynamic Table Full -->
    <div class="block">
        <div class="block-header">
            <h3 class="block-title"><?= $this->escapeHtml($title) ?></h3>
        </div>
        <div class="block-content">
            <!-- DataTables init on table by adding .js-dataTable-full class, functionality initialized in js/pages/base_tables_datatables.js -->
            <table class="table table-bordered table-striped js-dataTable-full">
                <thead>
                    <tr>
                        <th><?php echo $this->translate('ID');?></th>
                        <th><?php echo $this->translate('First name');?></th>
                        <th><?php echo $this->translate('Last name');?></th>
                        <td><?php echo $this->translate('Rate');?></td>
                        <th><?php echo $this->translate('Feedback');?></th>
                        <th><?php echo $this->translate('date');?></th>
                        <th class="text-center" style="width: 10%;"><?php echo $this->translate('Actions');?></th>
                    </tr>
                </thead>
                <tbody>
                    <?php if(count($feedbacks)):?>
                    <?php foreach ($feedbacks as $feedback) : ?>
                        <tr>
                            <td><?= $this->escapeHtml($feedback['id']) ?></td>
                            <td><?= $this->escapeHtml($feedback['firstname']) ?></td>
                            <td><?= $this->escapeHtml($feedback['lastname']) ?></td>
                            <td><?= $this->escapeHtml($feedback['rate']) ?></td>
                            <td><?= $this->escapeHtml($feedback['text']) ?></td>
                            <td><?= $this->escapeHtml($feedback['date']) ?></td>
                            <td>
                                <div class="btn-group">
                                    <a href="<?= $this->url('feedback', ['action' => 'edit', 'id' => $feedback['id']]) ?>" class="btn btn-xs btn-default" type="button" data-toggle="tooltip" title="<?php $this->translate('Edit Feedback');?>"><i class="fa fa-pencil"></i></a>
                                    <a href="<?= $this->url('feedback', ['action' => 'delete', 'id' => $feedback['id']]) ?>" class="btn btn-xs btn-default" type="button" data-toggle="tooltip" title="<?php $this->translate('Remove Feedback');?>"><i class="fa fa-times"></i></a>
                                </div>
                            </td>
                        </tr>
                    <?php endforeach; 
                    else:
                    ?>
                        <tr><td colspan="7"><?php echo $this->translate('No feedbacks found');?></td></tr>
                    <?php endif;?>
                </tbody>
            </table>
        </div>
    </div>
</div>
<!-- END Page Header -->
